export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const CLOSE_ALERT = 'CLOSE_ALERT';
export const TOGGLE_ISSUE_REQUEST = 'TOGGLE_ISSUE_REQUEST';
export const TOGGLE_ISSUE_SUCCESS = 'TOGGLE_ISSUE_SUCCESS';
